server:
  port: 18086
  max-http-header-size: 102400
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: http://192.168.198.88:9200
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.198.88
    port: 5672
    virtual-host: /lyc
    username: lyc
    password: 123
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 6
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug
